# Generated by Django 4.2.6 on 2023-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.CharField(max_length=200)),
                ("Type", models.CharField(max_length=100)),
                ("Date Registered", models.DateTimeField()),
                ("Status", models.CharField(default="To Do", max_length=20)),
            ],
        ),
    ]
