# Generated by Django 4.2.6 on 2023-10-27 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bug", "0003_alter_bug_status_alter_bug_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug",
            old_name="Type",
            new_name="bug_type",
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="Date Registered",
            new_name="report_date",
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="Status",
            new_name="status",
        ),
    ]
